import {
  Hospital,
  Department,
  Doctor,
  HospitalLocation,
  User,
  Appointment,
  QueueToken,
} from '../types.ts';

export const SEED_USERS: User[] = [
  {
    id: 'usr-patient-1',
    role: 'PATIENT',
    name: 'Ramesh Kumar',
    mobile: '9876543210',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'usr-doc-1',
    role: 'DOCTOR',
    name: 'Dr. Arjun Mehta',
    email: 'dr.mehta@hospital.gov.in',
    passwordHash: 'doctor123',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'usr-doc-2',
    role: 'DOCTOR',
    name: 'Dr. Rajesh Verma',
    email: 'dr.verma@hospital.gov.in',
    passwordHash: 'doctor123',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'usr-staff-1',
    role: 'STAFF',
    name: 'Vikas Sharma (OPD Counter In-charge)',
    email: 'staff@hospital.gov.in',
    passwordHash: 'staff123',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'usr-benefit-1',
    role: 'BENEFIT_DESK',
    name: 'Kavita Singh (Ayushman Mitra)',
    email: 'ayushman.desk@hospital.gov.in',
    passwordHash: 'ayushman123',
    createdAt: new Date().toISOString(),
  },
];

export const SEED_HOSPITALS: Hospital[] = [
  {
    id: 'hosp-1',
    name: 'All India Institute of Medical Sciences (AIIMS)',
    state: 'Delhi',
    district: 'New Delhi',
    address: 'Sri Aurobindo Marg, Ansari Nagar, New Delhi',
    pinCode: '110029',
    contactPhone: '011-26588500',
    facilities: [
      'Digital Queue Token Display',
      'Ayushman PM-JAY Helpdesk',
      'Jan Aushadhi Kendra',
      '24/7 Central Pharmacy',
      'Emergency Trauma Center',
      'Wheelchair / Stretcher Ramp Access',
      'Diagnostic Pathology Lab',
      'Echo & ECG Center',
    ],
    bedCount: 2478,
    active: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'hosp-2',
    name: 'Safdarjung Hospital & VMMC',
    state: 'Delhi',
    district: 'South West Delhi',
    address: 'Ring Road, Opposite AIIMS, New Delhi',
    pinCode: '110029',
    contactPhone: '011-26165060',
    facilities: [
      'OPD Online Registration Desk',
      'Ayushman Bharat Kiosk',
      'Government Free Medicine Counter',
      'Blood Bank & Component Unit',
      'Senior Citizen Fast-track Counter',
    ],
    bedCount: 1530,
    active: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'hosp-3',
    name: "King George's Medical University (KGMU)",
    state: 'Uttar Pradesh',
    district: 'Lucknow',
    address: 'Shah Mina Road, Chowk, Lucknow',
    pinCode: '226003',
    contactPhone: '0522-2257450',
    facilities: [
      'Digital Token Display Board',
      'PM-JAY Verification Desk',
      'State Health Scheme Counter',
      'Generic Medicine Dispensary',
      'Central Diagnostic Lab',
    ],
    bedCount: 4500,
    active: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'hosp-4',
    name: 'Sawai Man Singh (SMS) Hospital',
    state: 'Rajasthan',
    district: 'Jaipur',
    address: 'Jawahar Lal Nehru Marg, Ashok Nagar, Jaipur',
    pinCode: '302004',
    contactPhone: '0141-2560291',
    facilities: [
      'Chiranjeevi / PM-JAY Helpdesk',
      'Free Medicine Dispensary (DDC)',
      'Sub-center OPD Tokens',
      'Radiology & CT / MRI Wing',
    ],
    bedCount: 2200,
    active: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'hosp-5',
    name: 'Victoria Hospital (BMCRI)',
    state: 'Karnataka',
    district: 'Bengaluru Urban',
    address: 'Fort Road, Near City Market, Kalasipalya, Bengaluru',
    pinCode: '560002',
    contactPhone: '080-26701150',
    facilities: [
      'Ayushman Bharat Arogya Karnataka (AB-ArK) Desk',
      'Token Screen Display',
      'Pharmacy Counter 2B',
      'Dialysis Unit',
    ],
    bedCount: 1200,
    active: true,
    createdAt: new Date().toISOString(),
  },
];

export const SEED_DEPARTMENTS: Department[] = [
  // AIIMS Departments
  {
    id: 'dept-1',
    hospitalId: 'hosp-1',
    name: 'General Medicine',
    code: 'GEN-MED',
    description: 'Diagnosis and non-surgical treatment of adult diseases, fever, diabetes, hypertension',
    floor: '1st Floor',
    block: 'New OPD Block A',
  },
  {
    id: 'dept-2',
    hospitalId: 'hosp-1',
    name: 'Cardiology',
    code: 'CARDIO',
    description: 'Heart disease diagnosis, preventive care, ECG, and cardiovascular evaluations',
    floor: '2nd Floor',
    block: 'Cardio-Neuro Center',
  },
  {
    id: 'dept-3',
    hospitalId: 'hosp-1',
    name: 'Orthopedics',
    code: 'ORTHO',
    description: 'Bones, joints, spine, fracture treatment, arthritis, and musculoskeletal care',
    floor: '3rd Floor',
    block: 'New OPD Block B',
  },
  {
    id: 'dept-4',
    hospitalId: 'hosp-1',
    name: 'Pediatrics',
    code: 'PED',
    description: 'Infant, child and adolescent health, vaccination, pediatric fever & growth',
    floor: '1st Floor',
    block: 'Mother & Child Block',
  },
  {
    id: 'dept-5',
    hospitalId: 'hosp-1',
    name: 'ENT (Ear, Nose & Throat)',
    code: 'ENT',
    description: 'Ear infections, sinusitis, throat disorders, hearing assessments',
    floor: '2nd Floor',
    block: 'New OPD Block A',
  },
  {
    id: 'dept-6',
    hospitalId: 'hosp-1',
    name: 'Dermatology',
    code: 'DERM',
    description: 'Skin infections, allergy testing, chronic dermatitis and general skin conditions',
    floor: 'Ground Floor',
    block: 'OPD Extension',
  },
  // Safdarjung Departments
  {
    id: 'dept-7',
    hospitalId: 'hosp-2',
    name: 'General Medicine',
    code: 'GEN-MED',
    description: 'Adult primary consultation, seasonal illnesses, fever OPD',
    floor: '1st Floor',
    block: 'Main Hospital Block',
  },
  {
    id: 'dept-8',
    hospitalId: 'hosp-2',
    name: 'Cardiology',
    code: 'CARDIO',
    description: 'Cardiac OPD, chest discomfort screening, blood pressure management',
    floor: '2nd Floor',
    block: 'Super Speciality Block',
  },
  // KGMU Departments
  {
    id: 'dept-9',
    hospitalId: 'hosp-3',
    name: 'General Medicine',
    code: 'GEN-MED',
    description: 'Comprehensive adult medical OPD',
    floor: '1st Floor',
    block: 'Shatabdi Phase 1',
  },
  // SMS Hospital
  {
    id: 'dept-10',
    hospitalId: 'hosp-4',
    name: 'General Medicine',
    code: 'GEN-MED',
    description: 'General outpatient medical consultations',
    floor: '1st Floor',
    block: 'Charak Bhawan',
  },
  // Victoria
  {
    id: 'dept-11',
    hospitalId: 'hosp-5',
    name: 'General Medicine',
    code: 'GEN-MED',
    description: 'OPD General Physician Consultations',
    floor: '1st Floor',
    block: 'Centenary Block',
  },
];

export const SEED_DOCTORS: Doctor[] = [
  {
    id: 'doc-1',
    userId: 'usr-doc-1',
    hospitalId: 'hosp-1',
    departmentId: 'dept-1',
    name: 'Dr. Arjun Mehta',
    qualification: 'MBBS, MD (Medicine)',
    specialization: 'Internal Medicine & Infectious Fevers',
    roomNumber: 'Room 20',
    floor: '1st Floor',
    block: 'New OPD Block A',
    status: 'AVAILABLE',
    avgConsultMin: 8,
    availableDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
  },
  {
    id: 'doc-2',
    hospitalId: 'hosp-1',
    departmentId: 'dept-1',
    name: 'Dr. Sunita Rao',
    qualification: 'MBBS, MD (Internal Medicine)',
    specialization: 'Endocrinology & Lifestyle Disorders',
    roomNumber: 'Room 21',
    floor: '1st Floor',
    block: 'New OPD Block A',
    status: 'AVAILABLE',
    avgConsultMin: 10,
    availableDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
  },
  {
    id: 'doc-3',
    userId: 'usr-doc-2',
    hospitalId: 'hosp-1',
    departmentId: 'dept-2',
    name: 'Dr. Rajesh Verma',
    qualification: 'MBBS, MD, DM (Cardiology)',
    specialization: 'Preventive Cardiology & Hypertension',
    roomNumber: 'Room 12',
    floor: '2nd Floor',
    block: 'Cardio-Neuro Center',
    status: 'AVAILABLE',
    avgConsultMin: 12,
    availableDays: ['Monday', 'Wednesday', 'Friday'],
  },
  {
    id: 'doc-4',
    hospitalId: 'hosp-1',
    departmentId: 'dept-3',
    name: 'Dr. Priya Sharma',
    qualification: 'MBBS, MS (Orthopedics)',
    specialization: 'Joint Replacement & Spine Injury',
    roomNumber: 'Room 08',
    floor: '3rd Floor',
    block: 'New OPD Block B',
    status: 'AVAILABLE',
    avgConsultMin: 10,
    availableDays: ['Tuesday', 'Thursday', 'Saturday'],
  },
  {
    id: 'doc-5',
    hospitalId: 'hosp-1',
    departmentId: 'dept-4',
    name: 'Dr. Mohammed Imran',
    qualification: 'MBBS, MD (Pediatrics), DCH',
    specialization: 'General Pediatrics & Neonatal Care',
    roomNumber: 'Room 15',
    floor: '1st Floor',
    block: 'Mother & Child Block',
    status: 'AVAILABLE',
    avgConsultMin: 8,
    availableDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
  },
  {
    id: 'doc-6',
    hospitalId: 'hosp-1',
    departmentId: 'dept-5',
    name: 'Dr. Ananya Sen',
    qualification: 'MBBS, MS (ENT)',
    specialization: 'Otology & Head/Neck Disorders',
    roomNumber: 'Room 18',
    floor: '2nd Floor',
    block: 'New OPD Block A',
    status: 'BREAK',
    avgConsultMin: 10,
    availableDays: ['Monday', 'Wednesday', 'Saturday'],
  },
  // Safdarjung Doctor
  {
    id: 'doc-7',
    hospitalId: 'hosp-2',
    departmentId: 'dept-7',
    name: 'Dr. Vivek Malhotra',
    qualification: 'MBBS, MD (Medicine)',
    specialization: 'General Medicine & Tropical Fevers',
    roomNumber: 'Room 104',
    floor: '1st Floor',
    block: 'Main Hospital Block',
    status: 'AVAILABLE',
    avgConsultMin: 8,
    availableDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
  },
];

export const SEED_LOCATIONS: HospitalLocation[] = [
  // AIIMS Ground Floor
  {
    id: 'loc-1',
    hospitalId: 'hosp-1',
    name: 'Central OPD Registration & Token Kiosk',
    category: 'REGISTRATION',
    floor: 'Ground Floor',
    room: 'Counter 1 to 8',
    building: 'New OPD Block A',
    routeInstructions: [
      'Enter through Gate No. 2 (Main Hospital Entrance)',
      'Cross the security check at Front Porch',
      'Walk straight 30 meters into the central atrium',
      'Look for the blue sign boards: "OPD Registration Counters 1-8"',
    ],
    operatingHours: '07:30 AM - 11:30 AM',
  },
  {
    id: 'loc-2',
    hospitalId: 'hosp-1',
    name: 'Ayushman Bharat (PM-JAY) Help Desk',
    category: 'HELP_DESK',
    floor: 'Ground Floor',
    room: 'Counter 09 (Ayushman Mitra)',
    building: 'New OPD Block A',
    routeInstructions: [
      'Enter Ground Floor Central Atrium',
      'Proceed to the right side of the main registration counters',
      'Counter 9 has a dedicated tricolor "Ayushman Bharat / PM-JAY Helpdesk" signboard',
    ],
    operatingHours: '08:00 AM - 04:00 PM',
  },
  // AIIMS 1st Floor
  {
    id: 'loc-3',
    hospitalId: 'hosp-1',
    name: 'General Medicine OPD (Dr. Arjun Mehta & Team)',
    category: 'OPD',
    floor: '1st Floor',
    room: 'Room 20 & Room 21',
    building: 'New OPD Block A',
    routeInstructions: [
      'Take Elevator B or Central Staircase to the 1st Floor',
      'Turn left after exiting the elevator bank',
      'Follow the Blue Floor Line to Corridor A-1',
      'Room 20 is situated on your right side',
    ],
    operatingHours: '08:30 AM - 01:30 PM',
  },
  {
    id: 'loc-4',
    hospitalId: 'hosp-1',
    name: 'Pediatrics Clinic (Room 15)',
    category: 'OPD',
    floor: '1st Floor',
    room: 'Room 15',
    building: 'Mother & Child Block',
    routeInstructions: [
      'Take Bridge walkway from 1st Floor Block A to Mother & Child Block',
      'Walk past immunization bay',
      'Room 15 is on the left corridor with child-friendly mural',
    ],
    operatingHours: '09:00 AM - 01:00 PM',
  },
  // AIIMS 2nd Floor
  {
    id: 'loc-5',
    hospitalId: 'hosp-1',
    name: 'Cardiology OPD (Dr. Rajesh Verma)',
    category: 'OPD',
    floor: '2nd Floor',
    room: 'Room 12',
    building: 'Cardio-Neuro Center',
    routeInstructions: [
      'Take Lift 3 or 4 to 2nd Floor',
      'Turn right into Cardiology OPD Wing',
      'Room 12 is near the ECG waiting lounge',
    ],
    operatingHours: '09:00 AM - 02:00 PM',
  },
  {
    id: 'loc-6',
    hospitalId: 'hosp-1',
    name: 'Government Hospital Pharmacy (Free Medicine Counter)',
    category: 'PHARMACY',
    floor: '2nd Floor',
    room: 'Room 12B',
    building: 'New OPD Block A',
    routeInstructions: [
      'Entrance: Main Gate 2 Front Porch',
      'Step 1: Walk into Ground Floor Central Reception',
      'Step 2: Take Elevator bank (Lifts 1-4) or stairs to 2nd Floor',
      'Step 3: Exit lift and follow the prominent Yellow floor stripe',
      'Step 4: Room 12B — Central Medicine Dispensary & Pharmacy Counter',
    ],
    operatingHours: '08:30 AM - 04:30 PM',
  },
  // AIIMS 3rd Floor
  {
    id: 'loc-7',
    hospitalId: 'hosp-1',
    name: 'Orthopedics Clinic & Plaster Room',
    category: 'OPD',
    floor: '3rd Floor',
    room: 'Room 08',
    building: 'New OPD Block B',
    routeInstructions: [
      'Take Elevator bank to 3rd Floor',
      'Walk along the orthopedic corridor to Room 08',
      'Plaster room is immediately adjacent at Room 09',
    ],
    operatingHours: '08:30 AM - 01:30 PM',
  },
  {
    id: 'loc-8',
    hospitalId: 'hosp-1',
    name: 'Central Diagnostic Pathology Laboratory',
    category: 'LABORATORY',
    floor: '3rd Floor',
    room: 'Room 10',
    building: 'New OPD Block A',
    routeInstructions: [
      '3rd Floor central corridor',
      'Report sample collection at Counter A',
      'Pick up results at Counter B or digital QR kiosks',
    ],
    operatingHours: '08:00 AM - 03:00 PM',
  },
];

export const INITIAL_APPOINTMENTS: Appointment[] = [
  {
    id: 'apt-1',
    appointmentRef: 'SWQ-2026-08142',
    hospitalId: 'hosp-1',
    hospitalName: 'All India Institute of Medical Sciences (AIIMS)',
    departmentId: 'dept-1',
    departmentName: 'General Medicine',
    doctorId: 'doc-1',
    doctorName: 'Dr. Arjun Mehta',
    doctorRoom: 'Room 20',
    doctorFloor: '1st Floor',
    patientId: 'pat-1',
    patientName: 'Ramesh Kumar',
    patientMobile: '9876543210',
    patientAge: 45,
    date: new Date().toISOString().split('T')[0],
    timeSlot: '09:30 AM',
    visitReason: 'Routine health checkup and persistent mild fever',
    currentCondition: 'Fever and weakness for two days.',
    status: 'CHECKED_IN',
    benefitStatus: 'VERIFIED',
    benefitVerificationId: 'bv-1',
    queueTokenId: 'token-1',
    queueTokenNumber: 'A-27',
    checkedInAt: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 48 * 3600 * 1000).toISOString(),
  },
  {
    id: 'apt-2',
    appointmentRef: 'SWQ-2026-08143',
    hospitalId: 'hosp-1',
    hospitalName: 'All India Institute of Medical Sciences (AIIMS)',
    departmentId: 'dept-1',
    departmentName: 'General Medicine',
    doctorId: 'doc-1',
    doctorName: 'Dr. Arjun Mehta',
    doctorRoom: 'Room 20',
    doctorFloor: '1st Floor',
    patientId: 'pat-2',
    patientName: 'Geeta Devi',
    patientMobile: '9811223344',
    patientAge: 52,
    date: new Date().toISOString().split('T')[0],
    timeSlot: '10:00 AM',
    visitReason: 'Joint discomfort and high blood sugar follow-up',
    currentCondition: 'Knee swelling and blood sugar review.',
    status: 'CHECKED_IN',
    benefitStatus: 'VERIFICATION_PENDING',
    queueTokenId: 'token-2',
    queueTokenNumber: 'A-28',
    checkedInAt: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 24 * 3600 * 1000).toISOString(),
  },
  {
    id: 'apt-3',
    appointmentRef: 'SWQ-2026-08144',
    hospitalId: 'hosp-1',
    hospitalName: 'All India Institute of Medical Sciences (AIIMS)',
    departmentId: 'dept-1',
    departmentName: 'General Medicine',
    doctorId: 'doc-1',
    doctorName: 'Dr. Arjun Mehta',
    doctorRoom: 'Room 20',
    doctorFloor: '1st Floor',
    patientId: 'pat-3',
    patientName: 'Sunil Verma',
    patientMobile: '9711882233',
    patientAge: 38,
    date: new Date().toISOString().split('T')[0],
    timeSlot: '10:30 AM',
    visitReason: 'Dry cough and throat irritation',
    currentCondition: 'Throat irritation for past 4 days.',
    status: 'BOOKED',
    benefitStatus: 'NOT_VERIFIED',
    createdAt: new Date(Date.now() - 12 * 3600 * 1000).toISOString(),
  },
];

export const INITIAL_QUEUE_TOKENS: QueueToken[] = [
  {
    id: 'token-0',
    tokenNumber: 'A-26',
    hospitalId: 'hosp-1',
    departmentId: 'dept-1',
    doctorId: 'doc-1',
    doctorName: 'Dr. Arjun Mehta',
    roomNumber: 'Room 20',
    floor: '1st Floor',
    appointmentId: 'apt-prev',
    patientName: 'Suresh Patel',
    sequenceNumber: 26,
    status: 'IN_CONSULTATION',
    estimatedWaitMinutes: 0,
    date: new Date().toISOString().split('T')[0],
    calledAt: new Date(Date.now() - 6 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 40 * 60 * 1000).toISOString(),
  },
  {
    id: 'token-1',
    tokenNumber: 'A-27',
    hospitalId: 'hosp-1',
    departmentId: 'dept-1',
    doctorId: 'doc-1',
    doctorName: 'Dr. Arjun Mehta',
    roomNumber: 'Room 20',
    floor: '1st Floor',
    appointmentId: 'apt-1',
    patientName: 'Ramesh Kumar',
    sequenceNumber: 27,
    status: 'WAITING',
    estimatedWaitMinutes: 8,
    date: new Date().toISOString().split('T')[0],
    createdAt: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
  },
  {
    id: 'token-2',
    tokenNumber: 'A-28',
    hospitalId: 'hosp-1',
    departmentId: 'dept-1',
    doctorId: 'doc-1',
    doctorName: 'Dr. Arjun Mehta',
    roomNumber: 'Room 20',
    floor: '1st Floor',
    appointmentId: 'apt-2',
    patientName: 'Geeta Devi',
    sequenceNumber: 28,
    status: 'WAITING',
    estimatedWaitMinutes: 18,
    date: new Date().toISOString().split('T')[0],
    createdAt: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
  },
];
